namespace Kymeta.Cloud.Services.EnterpriseBroker.Models.Oracle.REST;

public class OracleOrganizationUpdateResponse
{
    public ulong PartyId { get; set; }
    public string PartyNumber { get; set; }
    public string SourceSystem { get; set; }
    public string SourceSystemReferenceValue { get; set; }
    public long OrganizationProfileId { get; set; }
    public string OrganizationName { get; set; }
    public object UniqueNameSuffix { get; set; }
    public string PartyUniqueName { get; set; }
    public string Type { get; set; }
    public string SalesProfileNumber { get; set; }
    public object OwnerPartyId { get; set; }
    public object OwnerPartyNumber { get; set; }
    public object OwnerEmailAddress { get; set; }
    public object OwnerName { get; set; }
    public object PrimaryContactPartyId { get; set; }
    public object PrimaryContactPartyNumber { get; set; }
    public object PrimaryContactSourceSystem { get; set; }
    public object PrimaryContactSourceSystemReferenceValue { get; set; }
    public object PrimaryContactName { get; set; }
    public object PrimaryContactJobTitle { get; set; }
    public object PrimaryContactEmail { get; set; }
    public object PrimaryContactPhone { get; set; }
    public bool ExistingCustomerFlag { get; set; }
    public object ExistingCustomerFlagLastUpdateDate { get; set; }
    public bool NamedFlag { get; set; }
    public object LastAssignmentDateTime { get; set; }
    public bool AssignmentExceptionFlag { get; set; }
    public string SalesProfileStatus { get; set; }
    public string IndustryCodeType { get; set; }
    public object IndustryCode { get; set; }
    public object ParentAccountPartyId { get; set; }
    public object ParentAccountPartyNumber { get; set; }
    public object ParentAccountSourceSystem { get; set; }
    public object ParentAccountSourceSystemReferenceValue { get; set; }
    public object ParentAccountName { get; set; }
    public object YearEstablished { get; set; }
    public object ControlYear { get; set; }
    public object YearIncorporated { get; set; }
    public object StockSymbol { get; set; }
    public object FiscalYearendMonth { get; set; }
    public object CurrentFiscalYearPotentialRevenueAmount { get; set; }
    public object PreferredFunctionalCurrency { get; set; }
    public object AnalysisFiscalYear { get; set; }
    public object NextFiscalYearPotentialRevenueAmount { get; set; }
    public string TaxpayerIdentificationNumber { get; set; }
    public object CertificationLevel { get; set; }
    public object CertificationReasonCode { get; set; }
    public object DUNSNumber { get; set; }
    public object DUNSCreditRating { get; set; }
    public object ParentDUNSNumber { get; set; }
    public object DomesticUltimateDUNSNumber { get; set; }
    public object GlobalUltimateDUNSNumber { get; set; }
    public object CEOName { get; set; }
    public object CEOTitle { get; set; }
    public bool PublicPrivateOwnershipFlag { get; set; }
    public object ImportIndicator { get; set; }
    public object ExportIndicator { get; set; }
    public object SmallBusinessIndicator { get; set; }
    public object WomanOwnedIndicator { get; set; }
    public bool GeneralServicesAdministrationFlag { get; set; }
    public object MinorityOwnedIndicator { get; set; }
    public object MinorityOwnedType { get; set; }
    public object RentOrOwnIndicator { get; set; }
    public object LaborSurplusIndicator { get; set; }
    public object OutOfBusinessIndicator { get; set; }
    public object HQBranchIndicator { get; set; }
    public object ParentOrSubsidiaryIndicator { get; set; }
    public object DisadvantageIndicator { get; set; }
    public object EmployeesAtPrimaryAddress { get; set; }
    public object EmployeesAtPrimaryAddressEstimation { get; set; }
    public object EmployeesAtPrimaryAddressMinimum { get; set; }
    public object EmployeesAtPrimaryAddressText { get; set; }
    public object EmployeesTotal { get; set; }
    public object TotalEmployeesEstimatedIndicator { get; set; }
    public object TotalEmployeesIndicator { get; set; }
    public object TotalEmployeesMinimumIndicator { get; set; }
    public object TotalEmployeesText { get; set; }
    public object OrganizationSize { get; set; }
    public object OrganizationType { get; set; }
    public object PrincipalTitle { get; set; }
    public object PrincipalName { get; set; }
    public object LegalStatus { get; set; }
    public object BusinessScope { get; set; }
    public object RegistrationType { get; set; }
    public object MissionStatement { get; set; }
    public object CorporationClass { get; set; }
    public object GrowthStrategyDescription { get; set; }
    public object CongressionalDistrictCode { get; set; }
    public object LineOfBusiness { get; set; }
    public object HomeCountry { get; set; }
    public object DoNotConfuseWith { get; set; }
    public object LocalActivityCode { get; set; }
    public object LocalActivityCodeType { get; set; }
    public object LocalBusinessIdentifier { get; set; }
    public object LocalBusinessIdentifierType { get; set; }
    public object SiebelLocation { get; set; }
    public object Comments { get; set; }
    public string CurrencyCode { get; set; }
    public string CorpCurrencyCode { get; set; }
    public object DataCloudStatus { get; set; }
    public object LastEnrichmentDate { get; set; }
    public string PartyStatus { get; set; }
    public string PartyType { get; set; }
    public string CreatedByModule { get; set; }
    public string CreatedBy { get; set; }
    public DateTime CreationDate { get; set; }
    public DateTime LastUpdateDate { get; set; }
    public string LastUpdateLogin { get; set; }
    public string LastUpdatedBy { get; set; }
    public object PreferredContactMethod { get; set; }
    public object PhoneContactPointType { get; set; }
    public object PhoneCountryCode { get; set; }
    public object PhoneAreaCode { get; set; }
    public object PhoneNumber { get; set; }
    public object PhoneExtension { get; set; }
    public object FormattedPhoneNumber { get; set; }
    public object RawPhoneNumber { get; set; }
    public object FaxContactPointType { get; set; }
    public object FaxCountryCode { get; set; }
    public object FaxAreaCode { get; set; }
    public object FaxNumber { get; set; }
    public object FaxExtension { get; set; }
    public object FormattedFaxNumber { get; set; }
    public object RawFaxNumber { get; set; }
    public object EmailContactPointType { get; set; }
    public object EmailFormat { get; set; }
    public object EmailAddress { get; set; }
    public object WebContactPointType { get; set; }
    public object URL { get; set; }
    public object PrimaryAddressId { get; set; }
    public string PartyNumberKey { get; set; }
    public object RecordSet { get; set; }
    public string SourceObjectType { get; set; }
    public bool FavoriteAccountFlag { get; set; }
    public bool UpdateFlag { get; set; }
    public bool DeleteFlag { get; set; }
    public object OrganizationTypeCode { get; set; }
    public object AddressNumber { get; set; }
    public object AddressElementAttribute1 { get; set; }
    public object AddressElementAttribute2 { get; set; }
    public object AddressElementAttribute3 { get; set; }
    public object AddressElementAttribute4 { get; set; }
    public object AddressElementAttribute5 { get; set; }
    public object AddressLine1 { get; set; }
    public object AddressLine2 { get; set; }
    public object AddressLine3 { get; set; }
    public object AddressLine4 { get; set; }
    public object Building { get; set; }
    public object City { get; set; }
    public object Country { get; set; }
    public object County { get; set; }
    public object FloorNumber { get; set; }
    public object PostalCode { get; set; }
    public object PostalPlus4Code { get; set; }
    public object Province { get; set; }
    public object State { get; set; }
    public object Mailstop { get; set; }
    public object AddressLinesPhonetic { get; set; }
    public object AddressType { get; set; }
    public object FormattedAddress { get; set; }
    public object AccountScore { get; set; }
    public object AccountScoringTier { get; set; }
    public object Description { get; set; }
    public object Keywords { get; set; }
    public int ConflictId { get; set; }
    public object DatafoxCompanyId { get; set; }
    public object UltimateParentPartyId { get; set; }
    public object UltimateParentName { get; set; }
    public object UltimateParentPartyNumber { get; set; }
    public object PhoneVerificationStatus { get; set; }
    public object PhoneVerificationDate { get; set; }
    public object FaxVerificationStatus { get; set; }
    public object FaxVerificationDate { get; set; }
    public object EmailVerificationStatus { get; set; }
    public object EmailVerificationDate { get; set; }
    public object PrimaryContactPhoneVerificationDate { get; set; }
    public object PrimaryContactEmailVerificationDate { get; set; }
    public bool PrimaryContactEmailDNC { get; set; }
    public bool PrimaryContactPhoneDNC { get; set; }
    public object PrimaryContactEmailVerificationStatus { get; set; }
    public object PrimaryContactPhoneVerificationStatus { get; set; }
    public int TotalAccountsInHierarchy { get; set; }
    public int TotalChildAccounts { get; set; }
    public object ParentAccountList { get; set; }
    public bool PrimaryContactDoEmailFlag { get; set; }
    public bool PrimaryContactDoCallFlag { get; set; }
    public OracleOrganizationUpdateResponseLink[] links { get; set; }
}

public class OracleOrganizationUpdateResponseLink
{
    public string rel { get; set; }
    public string href { get; set; }
    public string name { get; set; }
    public string kind { get; set; }
    public OracleOrganizationUpdateResponseProperties properties { get; set; }
}

public class OracleOrganizationUpdateResponseProperties
{
    public string changeIndicator { get; set; }
}